<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <MonoModBinaryDirectory Condition="'$(MonoModBinaryDirectory)' == ''">../../MonoMod.RuntimeDetour/bin/Release/net5.0</MonoModBinaryDirectory>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="MonoMod.RuntimeDetour" HintPath="$(MonoModBinaryDirectory)/MonoMod.RuntimeDetour.dll" />
    <Reference Include="MonoMod.Utils" HintPath="$(MonoModBinaryDirectory)/MonoMod.Utils.dll" />
    <PackageReference Include="Mono.Cecil" Version="0.11.6" />
  </ItemGroup>
</Project>
